### ISSUE TITLE
User Permission/Account System

### ISSUE THREAD

**Issue by douira** [tmshl/raspWatch#14]
Make a user and permissions system with passwords, login, and appropriate user actions. Not logged in users should still be able to view and create messages. Appropriate password security should also be implemented if needed.

**Comment by tmshl** [comment]
@douira: Could You design a login-page for this? Just a simple login, passwort, submit. It should display an error, if the password has not been correct. I do not know how to use bootstrap yet.

The template shoud be the file application/templates/user_login.php
The controller will provide these values:
$this->incorrect // If this page is shown after an incorrect password / login input
$this->login // The login the user used during the last attempt

The page should POST the values "login" and "password" to /user/login

**Comment by tmshl** [comment]
I will open a new branch with some skeleton-code soon. It may take a while, as I am learning how to use git.

**Comment by douira** [comment]
The current branch #1 feature should actually be merged into master. (generally always merge _towards_ master) I think it would b best if you created your new branch of the master branch.

**Comment by tmshl** [comment]
That's what I have done. New branch userlogin from master. Branch feature has already been added to master some time ago i suppose (?).

You can access now URL /user/login. Make sure to comment out accesscontrol in bootstrap.php

**Comment by douira** [comment]
I saw you created the new branch off of master. I've merged feature back into master to get rid of it. (I think you merged master into feature before...)

**Comment by douira** [comment]
What values/flags can I expect when the user name given is not in the system?

**Comment by douira** [comment]
Thought about it, just going to display "combination wrong" or so when one of them is incorrect. Better that way because user enumeration can be prevented then.

**Comment by tmshl** [comment]
branch merged, issue closed
