### ISSUE TITLE
Database naming

### ISSUE THREAD

**Issue by douira** [tmshl/raspWatch#3]
The naming in the database should be normalized to a unified and consistent style:

- in singular
- all lower case
- multiple words separated by underscores
- applied to database, table, and column names

**Comment by tmshl** [comment]
Let's do this better now. While working on the input branch  (#9) there is a lot of database access. I will adjust the database according to Your suggestions.

**Comment by douira** [comment]
Are you going to create a SQL dump from this? Maybe make another branch.

**Comment by tmshl** [comment]
branch: admin
will contain actions to setup and manage the page
there will be changes to the *Db classes too
(great benefit of OOP by the way - there will be only changes to the *Db classes as SQL-queries are bundled there)
