### ISSUE TITLE
Data receiving and testing

### ISSUE THREAD

**Issue by douira** [tmshl/raspWatch#9]
The page should be able to receive and save data that is sent to it via JSON. This function should be thoroughly tested with actual devices sending data over several days.

**Comment by tmshl** [comment]
That's what I'm working on now. Devices should POST a json-string to /messages/input.

**Comment by douira** [comment]
@tmshl just FYI: you can reference this issue by putting "#9" in your commits and pull request when you create it from a new branch. (I suggest you make a new branch when working on new features.) ;-)
